#!/bin/sh /etc/rc.common

START=99

MTDBLOCK7="mtdblock7"
OTHER_ROOT="/www/connect/res"
OTHER_ROOT_FLAG="/www/connect/res/other_data_file_root_dir"
MTD_PARTION_NAME="/dev/mtd7"

OTHER_DIR_SHOPINFO="/www/connect/res/shopInfo"

boot() {

	local mount_str
	
	mount_str=`mount | grep $MTDBLOCK7`
	[ -z "$mount_str" ] && {
	# not mount
		[ -d "$OTHER_ROOT" ] || {
			mkdir $OTHER_ROOT
		}
		mount -t jffs2 /dev/$MTDBLOCK7 $OTHER_ROOT -o rw,sync
		[ -f "$OTHER_ROOT_FLAG" ] || {
			#file system invalid
			umount $OTHER_ROOT
			flash_eraseall -j $MTD_PARTION_NAME
			mount -t jffs2 /dev/$MTDBLOCK7 $OTHER_ROOT -o rw,sync
			touch $OTHER_ROOT_FLAG
			[ -f "$OTHER_ROOT_FLAG" ] || {
				touch $OTHER_ROOT_FLAG
			}
		}
	}
	mkdir /tmp/others_res
	
	[ -f "$OTHER_DIR_SHOPINFO" ] && {
	    cp -rf $OTHER_DIR_SHOPINFO /etc/config/
		# don't need notify uhttpd
	}
}
