#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=95

MTDBLOCK7="mtdblock7"
OTHER_ROOT="/www/connect/res"
OTHER_ROOT_FLAG="/www/connect/res/other_data_file_root_dir"
MTD_PARTION_NAME="/dev/mtd7"

OTHER_DIR_SHOPINFO="/www/connect/res/shopInfo"

moun_mtd7() {

	local mount_str
	
	mount_str=`mount | grep $MTDBLOCK7`
	[ -z "$mount_str" ] && {
	# not mount
		[ -d "$OTHER_ROOT" ] || {
			mkdir $OTHER_ROOT
		}
		mount -t jffs2 /dev/$MTDBLOCK7 $OTHER_ROOT -o rw,sync
		[ -f "$OTHER_ROOT_FLAG" ] || {
			#file system invalid
			umount $OTHER_ROOT
			flash_eraseall -j $MTD_PARTION_NAME
			mount -t jffs2 /dev/$MTDBLOCK7 $OTHER_ROOT -o rw,sync
			touch $OTHER_ROOT_FLAG
			[ -f "$OTHER_ROOT_FLAG" ] || {
				touch $OTHER_ROOT_FLAG
			}
		}
	}
	mkdir /tmp/others_res
	
	[ -f "$OTHER_DIR_SHOPINFO" ] && {
	    cp -rf $OTHER_DIR_SHOPINFO /etc/config/
		# don't need notify uhttpd
	}
}

boot() {
	mount_root done
	rm -f /sysupgrade.tgz

	# process user commands
	[ -f /etc/rc.local ] && {
		sh /etc/rc.local
	}

	moun_mtd7
	
	# set leds to normal state
	. /etc/diag.sh
	set_state done
}
